/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pract5_MathOperations */

#ifndef _Included_pract5_MathOperations
#define _Included_pract5_MathOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pract5_MathOperations
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pract5_MathOperations_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pract5_MathOperations
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pract5_MathOperations_subtract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pract5_MathOperations
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pract5_MathOperations_multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pract5_MathOperations
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pract5_MathOperations_divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
